### ISSUE TITLE
wrong file type?

### ISSUE THREAD

**Issue by harryyyyy-666** [3ct0s/eclipse-grabber#16]
when i run it with the webhook command, it creates the file, however its a .py file? i need it a .exe? thanks

i also get this message
[-] Build Error: [WinError 2] The system cannot find the file specified

**Comment by addi00000** [comment]
> when i run it with the webhook command, it creates the file, however its a .py file? i need it a .exe? thanks
> 
> i also get this message [-] Build Error: [WinError 2] The system cannot find the file specified

The .py extension is a python extension. If you wanted to make it an executable you would

1. `python -m pip install PyInstaller`
2. `python -m PyInstaller "filename.py"`

If this works, great, if not, I can assist with further testing.
