### ISSUE TITLE
issue with  cmd 

### ISSUE THREAD

**Issue by Pitywithyou** [3ct0s/eclipse-grabber#17]
well, i get an error information when i try to run this command : powershell.exe -ExecutionPolicy Bypass -Command .\setup-files\setup-win.ps1 
the error looks like : -Command : Die Benennung "-Command" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1 (thats now german) translated by google translater it means : 
-Command : The term "-Command" was not recognized as the name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or the path (if included) is correct and try again.
In Line:1 Character:1)
+ -Command.\setup-files\setup-win.ps1
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (-Command:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by 3ct0s** [comment]
Hi There,
What version of Windows and PowerShell are you using? Are you sure you are inside the correct directory while executing this command?

**Comment by Pitywithyou** [comment]
I have the 21H2 Windows edition, i don't know which Powershell edition I have, I am sure that I use the right command

**Comment by 3ct0s** [comment]
That was not my question. My question was are you sure you are in the right directory/folder while running this command?

**Comment by Pitywithyou** [comment]
![IMG_20220210_172409.jpg](https://user-images.githubusercontent.com/98970324/153451094-7497fd17-f336-4d38-9ce4-63860a9f45e5.jpg) you mean this?

**Comment by Pitywithyou** [comment]
Nvm
