### ISSUE TITLE
error

### ISSUE THREAD

**Issue by NotASkidder** [3ct0s/eclipse-grabber#5]
i was just running build.py as you explained and i got this error

Build error: (Errno 2) No such file or directory 'wine'
![IMG_20220128_201650](https://user-images.githubusercontent.com/81571063/151607828-5db2a995-afde-4b21-b0e2-dc58e1a23a9f.jpg)

**Comment by NotASkidder** [comment]
oh jk, just see that the grab file is created, but is this error normal?

**Comment by NotASkidder** [comment]
is normal that the grab file is in .py? i mean i think it would be .exe

**Comment by 3ct0s** [comment]
Hi There,
Thanks for reaching out.

No, this issue is not normal. Did you go through the setup/installation steps without any problems? Did you follow the instructions written in the .MD files found in the **inst** directory? It appears wine is not installed on your system.

Please let us know.

**Comment by Kerago** [comment]
Hey, this i patched this issue! It will be patched in the next update!
