### ISSUE TITLE
error when i do it for 2 time

### ISSUE THREAD

**Issue by nkssnwn** [3ct0s/eclipse-grabber#6]
this error happens when I do the process for the second time and I don't know how to solve it

the first time i tried it it worked

![buggrabber](https://user-images.githubusercontent.com/98013370/151641959-b54a445e-12b0-48c4-b6ef-68579fbbb98a.png)

idk why

**Comment by 3ct0s** [comment]
Hi There,

This is a common problem when you try to do this process on Windows for the second time. Here is how to fix this.

1. Manually run the python-3.8.9.exe file and click on Uninstall (If it gives you an error move to the next step)
2. Again manually run the python-3.8.9.exe file and Click on Repair.
3. After the repair is done you should be able to run the PowerShell command again with no issues.

**Comment by nkssnwn** [comment]
It Works! Thx!

**Comment by Brandon981026** [comment]
i do the same thing tho but it came out this 
<img width="932" alt="image" src="https://user-images.githubusercontent.com/93974011/152469658-3b26f8fe-1c65-4e7f-8242-255dbaebae06.png">
<img width="946" alt="image" src="https://user-images.githubusercontent.com/93974011/152469733-f7f28283-fb10-4d54-933c-a773ff96a49f.png">
<img width="946" alt="image" src="https://user-images.githubusercontent.com/93974011/152469763-792ab7e3-9865-4741-907c-e954a2d3761e.png">
plz fix thankyou 
p.s my language is chinse just letting you know
